Repository codeit-part4-8team-project/main, pull requests merged in 2024-05, with the labels that each got.

#195 Feat: 공지사항 읽음 버튼 추가 및 채팅 인풋 ui 수정
  src/components/announcement/AnnouncementPageItem.tsx
  src/components/chat/ChatInput.tsx
Labels: 💡 Feature, :art: Style

#199 console.log 삭제
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/groupMemberInviteModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ControlDate.tsx
  src/components/SchedulesPage/ScheduleEditModal.tsx
  src/components/SchedulesPage/Time.tsx
  src/components/common/modal/Comment.tsx
  src/components/common/modal/CommentItem.tsx
  src/components/common/modal/CommentPageination.tsx
  src/components/common/modal/GroupList.tsx
  src/components/common/modal/ModalCalendarInput.tsx
  src/components/common/modal/ReplyItem.tsx
  src/hooks/useIssue.ts
Labels: :hammer_and_wrench: Refactor

#198 빌드오류 수정
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/Schedules.tsx
Labels: :bug: Bug Fix

#200 Fix: 회원가입시 oauth로 받아온 사진이 있어도 빈 사진으로 뜨는 문제 수정
  src/components/SignupPage/EnterUserStepContent.tsx
Labels: :bug: Bug Fix

#201 코드정리
  src/components/SchedulesPage/AddScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ModalDateCell.tsx
Labels: :hammer_and_wrench: Refactor
