Repository codeit-part4-8team-project/main, pull requests merged in 2024-03, with the labels that each got.

#5 Feat: TailwindCSS, global style 셋팅
  .prettierrc.json
  package-lock.json
  package.json
  src/index.css
  src/main.tsx
  tailwind.config.js
Labels: 💡 Feature

#7 Style: 프리티어 import문 정렬 기준 추가 및 수정
  .prettierrc.json
Labels: :art: Style

#9 Nav soeun
  public/plus.svg
  src/components/common/Nav.tsx
  src/pages/HomePage.tsx
  src/pages/SchedulesPage.tsx
Labels: :art: Style

#10 Feat: Button common components, Refactor: Modal Img
  public/images/Close.svg
  public/images/Plus.svg
  src/components/common/Button.tsx
  src/components/common/Modal.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#11 Design: 사이드바 UI 구조
  src/components/common/SideBar.tsx
  src/pages/TeamsPage.tsx
Labels: :art: Style

#12 Design: 팀 페이지 - 칸반보드 UI 구조
  public/check.svg
  public/profile.svg
  src/components/issue/IssueCards.tsx
  src/components/issue/KanbanBoard.tsx
  src/components/issue/TaskCards.tsx
  src/pages/TeamsPage.tsx
Labels: :art: Style

#13 Design: 팀 페이지 - 공지사항 UI 구조
  public/circle.svg
  public/closed.svg
  src/components/announcement/AnnouncementBoard.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/pages/TeamsPage.tsx
Labels: :art: Style

#14 Design: 팀 페이지 - 페이지 UI 구조
  src/components/TeamBar.tsx
  src/pages/TeamsPage.tsx
Labels: :art: Style

#15 Mypage 작업
  package-lock.json
  package.json
  public/data/Mock.json
  public/data/Teams.json
  public/images/userImgNull.svg
  src/App.tsx
  src/components/TeamsHistory.tsx
  src/components/common/Button.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
Labels: 💡 Feature, :gear: Setting

#18 Schedules page soeun
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ControlDate.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/SchedulesPage/WeekBox.tsx
  src/pages/SchedulesPage.tsx
Labels: 💡 Feature, :art: Style

#19 Modal 완성
  public/data/TeamsMember.json
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/common/ModalInput.tsx
  src/components/common/ModalLayout.tsx
Labels: 💡 Feature, :art: Style

#21 함수 이름 변경해서 다시 올립니다!
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/ScheduleModal.tsx
Labels: :hammer_and_wrench: Refactor

#23 Feat: 링크 및 모달창 버튼 클릭 이벤트 작업
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/TeamBar.tsx
  src/components/announcement/AnnouncementBoard.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/components/common/Nav.tsx
  src/components/common/SideBar.tsx
  src/components/issue/KanbanBoard.tsx
  src/pages/TeamsPage.tsx
Labels: 💡 Feature

#25 Design: 사이드바 UI 구현
  package-lock.json
  public/assets/bell-circle.svg
  public/assets/bell-dark.svg
  public/assets/box-light.svg
  public/assets/box-off.svg
  public/assets/box-on.svg
  public/assets/calendar-dark.svg
  public/assets/calendar-off.svg
  public/assets/calendar-on.svg
  public/assets/chat-light.svg
  public/assets/check-circle-light.svg
  public/assets/check-light.svg
  public/assets/close-light.svg
  public/assets/globe-dark.svg
  public/assets/globe-light.svg
  public/assets/green-dot.svg
  public/assets/info-circle-light.svg
  public/assets/list-check-light.svg
  public/assets/megaphone-light.svg
  public/assets/more-light.svg
  public/assets/people-light.svg
  public/assets/pin-light.svg
  public/assets/plus-circle-dark.svg
  public/assets/plus-circle-light.svg
  public/assets/plus-light.svg
  public/assets/profile-large.svg
  public/assets/profile-small.svg
  public/assets/section-off.svg
  public/assets/section-on.svg
  public/assets/sliders-dark.svg
  public/assets/stack-light.svg
  src/components/common/SideBar.tsx
  src/components/common/SideBar/BoardList.tsx
  src/components/common/SideBar/GroupList.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/constants.ts
  src/pages/SchedulesPage.tsx
  src/pages/TeamSchedulesPage.tsx
  src/pages/TeamsPage.tsx
Labels: 💡 Feature, :art: Style

#26 Design: 공지사항 컴포넌트 UI 구현
  .prettierrc.json
  public/assets/arrow-down-dark.png
  public/assets/check-circle-dark.svg
  public/assets/hidden-dark.svg
  public/assets/megaphone-dark.svg
  src/components/announcement/AnnouncementBoard.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/components/common/SideBar/BoardList.tsx
  src/components/common/SideBar/GroupList.tsx
  src/components/common/SideBar/SideBar.tsx
Labels: :art: Style

#24 Feat: modal Context, usemodal 구현
  src/App.tsx
  src/components/Modal/AlertModal.tsx
  src/components/ModalWrapper.tsx
  src/components/common/ModalLayout.tsx
  src/components/common/TextButton.tsx
  src/contexts/ModalProvider.tsx
  src/index.css
  src/pages/SigninPage.tsx
Labels: 💡 Feature

#28 Feat: Make MainPage calendar UI
  .gitignore
  src/components/MainPage/ControlDate.tsx
  src/components/MainPage/DateBox.tsx
  src/components/MainPage/MainSchedules.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/pages/MainPage.tsx
Labels: 💡 Feature

#29 Design: Nav바 새로운 디자인 수정
  pathtonpm-cache/_update-notifier-last-checked
  public/assets/Logo.svg
  public/assets/ProfileIcon.svg
  public/assets/bellFill.svg
  src/components/common/Nav.tsx
Labels: :art: Style

#27 teamMemberList 구현, 멤버이미지 클릭시 모달창 구현
  public/data/TeamsMember.json
  src/components/Modal/MemberProfile.tsx
  src/components/TeamMemberList.tsx
Labels: 💡 Feature

#30 Design: 칸반보드 UI 구현
  src/components/common/ProfileStack.tsx
  src/components/issue/IssueCards.tsx
  src/components/issue/KanbanBoard.tsx
  src/components/issue/TaskCards.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/pages/TeamsPage.tsx
Labels: 💡 Feature, :art: Style

#32 Refactor: 모달시스템 설명 주석 추가 및 리팩터링
  src/components/ModalWrapper.tsx
  src/contexts/ModalProvider.tsx
  src/pages/SigninPage.tsx
Labels: :hammer_and_wrench: Refactor

#35 Design: 사이드바 ui 수정 및 추가
  public/assets/folder-off.svg
  public/assets/folder-on.svg
  public/assets/kebab-light.svg
  public/assets/tooltip-arrow.svg
  src/components/common/SideBar/BoardList.tsx
  src/components/common/SideBar/DropDown.tsx
  src/components/common/SideBar/GroupList.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/constants.ts
  src/components/common/ToolTip.tsx
  src/components/common/test.tsx
  src/pages/SchedulesPage.tsx
  src/pages/TeamSchedulesPage.tsx
  src/pages/TeamsPage.tsx
Labels: 💡 Feature, :art: Style

#38 Feat: 사이드바 - 현재 페이지에 해당하는 버튼에 포커스 ui 적용
  src/components/common/SideBar/BoardList.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/constants.ts
Labels: 💡 Feature, :art: Style

#40 Setting: Add color variable on tailwindconfig
  tailwind.config.js
Labels: :gear: Setting

#39 캘린더 context로 관리, 나의 캘린더 페이지 ui 수정, 주간 월간 캘린더 합치기
  public/assets/My calendar.svg
  public/assets/_allow-left-all.svg
  public/assets/_allow-left.svg
  public/assets/_allow-right-all.svg
  public/assets/_allow-right.svg
  public/assets/check-circle-fill-dark.svg
  public/assets/check-circle-fill.svg
  public/assets/color chip-blue.svg
  public/assets/color chip-green.svg
  public/assets/color chip-yellow.svg
  public/assets/profile chip.svg
  src/App.tsx
  src/components/MainPage/ControlDate.tsx
  src/components/MainPage/DateBox.tsx
  src/components/MainPage/MainSchedules.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ControlDate.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/SchedulesPage/WeekBox.tsx
  src/components/common/Nav.tsx
  src/contexts/CalenarProvider.tsx
  src/pages/SchedulesPage.tsx
  src/pages/TeamSchedulesPage.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#41 Feat: signin, signup UI 와 공통 button component 구현
  public/assets/check-circle-fill-dark.svg
  public/assets/check-circle-fill-light.svg
  public/assets/logo-github.svg
  public/assets/logo-google.svg
  public/assets/logo-kakao.svg
  src/components/SignupPage/CheckboxInput.tsx
  src/components/SignupPage/CompleteStepContent.tsx
  src/components/SignupPage/EnterUserStepContent.tsx
  src/components/SignupPage/SignupLayout.tsx
  src/components/SignupPage/ToSStepContent.tsx
  src/components/common/TextButton.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
Labels: 💡 Feature

#43 Design: 메인 페이지 ui 높이 수정 및 색상 변수 적용
  src/components/announcement/AnnouncementBoard.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/components/common/BoardSection.tsx
  src/components/common/SideBar/DropDown.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/ToolTip.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/pages/MainPage.tsx
Labels: :art: Style

#44 Refactor: 기본 레이아웃을 공통 컴포넌트로 분리
  src/components/common/Board.tsx
  src/components/common/PageLayout.tsx
  src/pages/MainPage.tsx
Labels: :art: Style

#48 Setting: tailwind Typography 설정
  tailwind.config.js
Labels: :gear: Setting

#45 Design: 카드 컴포넌트가 없을 때 보여줄 ui 추가
  src/components/announcement/AnnouncementBoard.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/components/common/NoCard.tsx
  src/components/kanbanBoard/IssueList.tsx
Labels: :hammer_and_wrench: Refactor, :art: Style

#50 Fix: sideBar 디렉토리 이름 변경으로 발생한 문제 해결
  src/components/common/sideBar/BoardList.tsx
  src/components/common/sideBar/DropDown.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/constants.ts
Labels: :bug: Bug Fix

#49 Style: 텍스트 스타일 변수 적용 및 코드 스타일 컨벤션에 맞추어 수정
  src/components/TeamBar.tsx
  src/components/announcement/AnnouncementBoard.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/components/common/Board.tsx
  src/components/common/BoardSection.tsx
  src/components/common/NoCard.tsx
  src/components/common/PageLayout.tsx
  src/components/common/ToolTip.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/pages/TeamsPage.tsx
Labels: :hammer_and_wrench: Refactor, :art: Style

#51 Refactor: SVG컴포넌트화 셋팅
  src/assets/AllowDownIcon.tsx
  src/assets/AllowLeftAllIcon.tsx
  src/assets/AllowLeftIcon.tsx
  src/assets/AllowRightAllIcon.tsx
  src/assets/AllowRightIcon.tsx
  src/assets/BellIcon.tsx
  src/assets/BoxIcon.tsx
  src/assets/CalendarIcon.tsx
  src/assets/Chat4Icon.tsx
  src/assets/Check2CircleIcon.tsx
  src/assets/CheckCircleFill.tsx
  src/assets/CheckIcon.tsx
  src/assets/CloseIcon.tsx
  src/assets/FolderIcon.tsx
  src/assets/ListCheckIcon.tsx
  src/assets/MeatbollsIcon.tsx
  src/assets/MegaphoneIcon.tsx
  src/assets/PeopleIcon.tsx
  src/assets/PinAngleIcon.tsx
  src/assets/PlusCircleIcon.tsx
  src/assets/PlusIcon.tsx
  src/assets/Sliders3Icon.tsx
  src/assets/StackIcon.tsx
  src/assets/ViewListIcon.tsx
  src/types/iconProps.ts
Labels: :hammer_and_wrench: Refactor

#53 스캐줄 페이지 리팩토링 메인 페이지 스캐줄 적용
  public/assets/check-circle-fill-dark.svg
  src/components/MainPage/MainSchedules.tsx
  src/components/MainPage/WeekArr.tsx
  src/components/MainPage/WeekDisplay.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ControlDate.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/SchedulesPage/WeekBox.tsx
  src/components/common/Nav.tsx
  src/components/common/sideBar/SideBar.tsx
  src/pages/MainPage.tsx
  src/pages/SchedulesPage.tsx
Labels: :bug: Bug Fix, :hammer_and_wrench: Refactor

#55 메인페이지 캘린더 UI 수정, 모달 캘린더 UI 완성
  src/components/MainPage/MainSchedules.tsx
  src/components/ModalCalenar/ModalCalendar.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ControlDate.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/common/BoardSection.tsx
  src/contexts/CalenarProvider.tsx
  src/pages/TeamSchedulesPage.tsx
Labels: 💡 Feature, :art: Style

#58 Refactor: 기존의 svg 아이콘 컴포넌트로 변경
  src/assets/ClosedIcon.tsx
  src/assets/ColorChipIcon.tsx
  src/assets/ProfileIcon.tsx
  src/assets/TipArrow.tsx
  src/components/TeamBar.tsx
  src/components/announcement/AnnouncementCards.tsx
  src/components/common/BoardSection.tsx
  src/components/common/ToolTip.tsx
  src/components/common/sideBar/BoardList.tsx
  src/components/common/sideBar/DropDown.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/constants.ts
  src/components/common/sideBar/constants.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/test.tsx
  src/pages/MainPage.tsx
  src/pages/MyIssuesPage.tsx
  src/pages/TeamsPostsPage.tsx
Labels: :hammer_and_wrench: Refactor, :art: Style

#62 Feat: 소셜로그인 구현 & Refactor: useAxios 타입 수정
  src/App.tsx
  src/components/SignupPage/EnterUserStepContent.tsx
  src/components/SignupPage/SignupLayout.tsx
  src/components/SignupPage/ToSStepContent.tsx
  src/components/common/Input.tsx
  src/hooks/useAxios.ts
  src/pages/OauthRedirectPage.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
  src/types/user.ts
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#60 모달창 리팩토링 및 그룹초대장 일정추가 ui 완성
  src/components/Modal/AlertGroupModal.tsx
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/ModalAtuom/ModalMemberList.tsx
  src/components/common/modal/ModalCalendar.tsx
  src/components/common/modal/ModalCalendarInput.tsx
  src/components/common/modal/ModalColorToggle.tsx
  src/components/common/modal/ModalForm.tsx
  src/components/common/modal/ModalFormBorder.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/ModalLabel.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalMemberList.tsx
  src/pages/HomePage.tsx
  src/pages/TeamsPage.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#65 Feat: mock데이터로 월별 캘린더 데이터 넣기, 필터체크 아이콘 컴포넌트 추가, 캘린더 UI 수정
  public/data/GroupFilter.json
  public/data/GroupFilterTeam.json
  public/data/IdSchedule.json
  public/data/TeamSchedule.json
  src/assets/FilterCheckIconDark.tsx
  src/assets/FilterCheckIconLight.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/SchedulesPage/Schedules.tsx
Labels: 💡 Feature, :art: Style

#67 Design: 자유게시판 페이지 UI 구현
  src/components/common/BoardSection.tsx
  src/components/posts/BulletinBoard.tsx
  src/components/posts/Post.tsx
  src/mockdata/postData.ts
  src/pages/TeamsPostsPage.tsx
  src/types/postTypes.ts
Labels: :art: Style

#66 Design: 이슈 페이지 UI 구현
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/mockdata/issueData.ts
  src/pages/MainPage.tsx
  src/pages/MyIssuesPage.tsx
  src/types/issueTypes.ts
  tailwind.config.js
Labels: :hammer_and_wrench: Refactor, :art: Style

#68 Feat: 토큰 갱신 로직 구현
  src/hooks/useAxios.ts
  src/pages/OauthRedirectPage.tsx
Labels: 💡 Feature

#71 Feat: user context 구현
  src/App.tsx
  src/contexts/UserProvider.tsx
  src/hooks/useAxios.ts
Labels: 💡 Feature

#78 Feat: 사이드바 / 이슈 / 팀 백엔드 api 연동
  src/components/TeamsPage/TeamBar.tsx
  src/components/TeamsPage/TeamPageLayout.tsx
  src/components/common/NoCard.tsx
  src/components/common/sideBar/BoardList.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/constants.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/contexts/TeamProvider.tsx
  src/pages/team/TeamContents.tsx
  src/pages/team/TeamKanban.tsx
  src/pages/team/TeamMembers.tsx
  src/pages/team/TeamNotice.tsx
  src/types/issueTypes.ts
  src/types/teamTypes.ts
Labels: 💡 Feature

#79 Feat: 회원가입 페이지 완성
  src/assets/CheckCircleFill.tsx
  src/assets/ProfileIcon.tsx
  src/components/SignupPage/CheckboxInput.tsx
  src/components/SignupPage/CompletionStepContent.tsx
  src/components/SignupPage/EnterUserStepContent.tsx
  src/components/SignupPage/SignupLayout.tsx
  src/components/SignupPage/ToSStepContent.tsx
  src/components/common/Input.tsx
  src/contexts/SignupStepProvider.tsx
  src/contexts/UserProvider.tsx
  src/hooks/useAxios.ts
  src/pages/OauthRedirectPage.tsx
  src/pages/SignupPage.tsx
Labels: 💡 Feature

#81 Feat: 자유게시판 ui 수정 및 데이터 연동 + TeamContext 리팩토링
  src/App.tsx
  src/assets/GroupIcon.tsx
  src/assets/HeartIcon.tsx
  src/components/Post/PostItem.tsx
  src/components/Post/PostList.tsx
  src/components/TeamsPage/Tabs/TabsList.tsx
  src/components/TeamsPage/TeamBar.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/components/posts/BulletinBoard.tsx
  src/components/posts/Post.tsx
  src/contexts/TeamProvider.tsx
  src/hooks/usePost.ts
  src/lib/formatDate.ts
  src/mockdata/postData.ts
  src/pages/MyPostsPage.tsx
  src/pages/TeamsPostsPage.tsx
  src/pages/team/TeamBoard.tsx
  src/pages/team/TeamPostsPage.tsx
  src/types/postTypes.ts
  src/types/teamTypes.ts
Labels: 💡 Feature, :hammer_and_wrench: Refactor, :art: Style

#85 Feat: team/:teamId/members 페이지 UI 완성
  src/components/common/BoardSection.tsx
  src/components/common/TextButton.tsx
  src/components/members/MemberList.tsx
  src/components/members/MemberRow.tsx
  src/constants/Team.tsx
  src/constants/constants.tsx
  src/pages/UserPage.tsx
  src/pages/team/TeamMembers.tsx
  src/pages/team/TeamPage.tsx
  src/types/teamTypes.ts
  tailwind.config.js
Labels: 💡 Feature

#91 Feat: Private Routes 구현 & Fix: 콘솔 경고 제거
  src/App.tsx
  src/assets/AllowRightIcon.tsx
  src/assets/CloseIcon.tsx
  src/assets/ClosedIcon.tsx
  src/assets/FilterCheckIconDark.tsx
  src/assets/GroupIcon.tsx
  src/assets/PlusCircleIcon.tsx
  src/components/members/MemberList.tsx
  src/contexts/UserProvider.tsx
  src/hooks/useAxios.ts
  src/routes/PrivateRoutes.tsx
Labels: :bug: Bug Fix, 💡 Feature

#93 Refactor: 페이지 이름 및 페이지 관련 상수 파일 통일
  src/components/TeamsPage/Tabs/TabsList.tsx
  src/components/TeamsPage/Tabs/constants.tsx
  src/components/TeamsPage/TeamBar.tsx
  src/components/TeamsPage/TeamTab.tsx
  src/components/announcement/AnnouncementList.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/common/sideBar/BoardList.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/common/sideBar/constants.tsx
  src/constants/Page.tsx
  src/constants/constants.tsx
  src/pages/UserIssuesPage.tsx
  src/pages/UserMainPage.tsx
  src/pages/UserMyPage.tsx
  src/pages/UserPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamAnnouncementsPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/pages/team/TeamPage.tsx
Labels: :hammer_and_wrench: Refactor

#94 Groupmodal pillgyeom
  src/App.tsx
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/DetailsScheduleModal.tsx
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/InvitationGroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/NotMeIssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/common/modal/ModalMemberList.tsx
  src/pages/HomePage.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor, :art: Style

#97 Feat: 페이지네이션 구현
  src/assets/PageArrowLeftIcon.tsx
  src/assets/PageArrowRightIcon.tsx
  src/components/Post/PostList.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/common/BoardSection.tsx
  src/components/common/pagenation/PageNumber.tsx
  src/components/common/pagenation/Pagenation.tsx
  src/constants/Page.tsx
  src/contexts/PageProvider.tsx
  src/hooks/useAnnouncement.ts
  src/hooks/usePost.ts
  src/pages/UserMainPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamAnnouncementsPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/pages/team/TeamPostsPage.tsx
Labels: 💡 Feature

#99 Design: UI 수정 및 필요한 요소 추가
  src/assets/InviteIcon.tsx
  src/assets/PencilIcon.tsx
  src/components/Post/PostItem.tsx
  src/components/Post/PostList.tsx
  src/components/TeamsPage/TeamBar.tsx
  src/components/TeamsPage/TeamPageLayout.tsx
  src/components/TeamsPage/TeamTab.tsx
  src/components/announcement/AnnouncementItem.tsx
  src/components/announcement/AnnouncementList.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/common/Board.tsx
  src/components/common/BoardSection.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/NoCard.tsx
  src/components/common/ProfileStack.tsx
  src/components/common/UserPageLayout.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/kanbanBoard/IssueItem.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/hooks/useIssue.ts
  src/lib/getProfileImgs.ts
  src/pages/UserIssuesPage.tsx
  src/pages/UserMainPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamAnnouncementsPage.tsx
  src/pages/team/TeamIssuesPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/pages/team/TeamPostsPage.tsx
  src/types/postTypes.ts
Labels: :art: Style
