Repository codeit-part4-8team-project/main, pull requests merged in 2024-04, with the labels that each got.

#101 Calendar soeun
  public/data/TeamSchedule.json
  public/data/TeamsMember.json
  src/components/MainPage/MainSchedules.tsx
  src/components/MainPage/WeekDisplay.tsx
  src/components/Modal/GroupModal.tsx
  src/components/SchedulesPage/AddScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/common/BoardSection.tsx
  src/components/common/Nav.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/contexts/CalenarProvider.tsx
  src/contexts/UserProvider.tsx
  src/hooks/teamIdGet.ts
  src/hooks/useAxios.ts
  src/pages/SchedulesPage.tsx
  src/pages/UserMainPage.tsx
  src/pages/team/TeamCalendar.tsx
  src/pages/team/TeamMainPage.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#102 Design: 자잘한 UI 수정
  src/components/Post/PostList.tsx
  src/components/SchedulesPage/ControlDate.tsx
  src/components/TeamsPage/TeamBar.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/common/BoardSection.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/sideBar/SideBar.tsx
  src/constants/defaultPageData.ts
  src/pages/UserMainPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/types/teamTypes.ts
Labels: :art: Style

#103 Fix: 데이터 불러오기 관련 문제 해결
  src/components/TeamsPage/TeamBar.tsx
  src/components/kanbanBoard/IssueItem.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/pages/UserMainPage.tsx
  src/pages/team/TeamIssuesPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/types/issueTypes.ts
Labels: :bug: Bug Fix, :art: Style

#104 Feat: user/:userID/mypage 구현
  src/components/Modal/EditProfileModal.tsx
  src/components/Modal/ManageTeamHistoryModal.tsx
  src/components/ModalWrapper.tsx
  src/components/Mypage/MyProfileCard.tsx
  src/components/Mypage/MyTeamHistory.tsx
  src/components/Mypage/MyTeamHistoryRow.tsx
  src/components/Mypage/MyTeamHistoryTable.tsx
  src/components/Mypage/NoTeamRow.tsx
  src/components/common/BoardSection.tsx
  src/components/common/Dropdown.tsx
  src/components/common/EditProfileForm.tsx
  src/components/common/card/ProfileCard.tsx
  src/constants/Page.tsx
  src/constants/Team.tsx
  src/contexts/PageProvider.tsx
  src/contexts/UserProvider.tsx
  src/hooks/useMyTeam.ts
  src/pages/UserMyPage.tsx
  src/types/teamTypes.ts
  src/types/user.ts
Labels: 💡 Feature

#106 Feat: 칸반보드 drag-and-drop 기능 구현
  src/assets/InviteIcon.tsx
  src/assets/PencilIcon.tsx
  src/components/kanbanBoard/IssueItem.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/contexts/IssueProvider.tsx
  src/hooks/useIssue.ts
  src/pages/UserIssuesPage.tsx
  src/pages/UserMainPage.tsx
  src/pages/team/TeamIssuesPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/types/issueTypes.ts
Labels: 💡 Feature

#114 Feat: team/:teamId/members 페이지 완성
  src/App.tsx
  src/components/common/Dropdown.tsx
  src/components/members/MemberBoard.tsx
  src/components/members/MemberList.tsx
  src/components/members/MemberRow.tsx
  src/components/members/MemberTable.tsx
  src/constants/Team.tsx
  src/constants/defaultPageData.ts
  src/contexts/PageProvider.tsx
  src/hooks/useAxios.ts
  src/hooks/useMember.ts
  src/pages/team/TeamMembers.tsx
  src/types/teamTypes.ts
Labels: 💡 Feature

#113 Fixed: 빌드 시 오류 수정& 네브바 데이터 연동, 시간 설정 컴포넌트 생성
  src/assets/DarkGroupIcon.tsx
  src/components/SchedulesPage/AddScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/SchedulesPage/Time.tsx
  src/components/common/Nav.tsx
  src/contexts/CalenarProvider.tsx
  src/pages/HomePage.tsx
  src/pages/TeamSchedulesPage.tsx
Labels: :bug: Bug Fix, 💡 Feature

#115 Fix: useMember.tsx 로 인한 유저페이지 에러 수정
  src/hooks/useMember.ts
Labels: :bug: Bug Fix

#116 Feat: 공지사항 고정 기능 추가
  src/components/announcement/AnnouncementItem.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/common/ItemDropDown.tsx
Labels: 💡 Feature

#118 Feat: 시간설정 부분 스크롤 추가, 네브바 알림창 설정
  src/components/SchedulesPage/Time.tsx
  src/components/common/Nav.tsx
Labels: 💡 Feature

#119 Feat: 마이페이지 완성
  src/components/Modal/EditProfileModal.tsx
  src/components/Modal/ManageTeamHistoryModal.tsx
  src/components/Mypage/MyTeamHistory.tsx
  src/components/Mypage/MyTeamHistoryRow.tsx
  src/components/Mypage/MyTeamHistoryTable.tsx
  src/components/common/Input.tsx
  src/pages/UserMyPage.tsx
Labels: 💡 Feature

#122 Fix: errorChores
  src/components/Modal/AlertModal.tsx
  src/components/Modal/DetailsScheduleModal.tsx
  src/components/Modal/FreeBoardDetail.tsx
  src/components/Modal/FreeBoardEdit.tsx
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/InvitationGroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/NotMeIssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/TeamMemberList.tsx
  src/components/common/modal/ModalCalendarInput.tsx
  src/components/common/modal/ModalColorToggle.tsx
  src/components/common/modal/ModalForm.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/hooks/teamIdGet.ts
  src/pages/HomePage.tsx
Labels: :bug: Bug Fix, :hammer_and_wrench: Refactor

#123 랜딩페이지
  public/assets/b092b2f4d5e614fd0d65600fb2b5ce08 1.png
  src/components/landing/LandingNav.tsx
  src/components/landing/Section.tsx
  src/components/landing/SectionItem.tsx
  src/pages/HomePage.tsx
Labels: 💡 Feature

#124 Feat: 로그인 후 리다이렉트 동작 개선
  src/App.tsx
  src/components/SignupPage/CompleteStepContent.tsx
  src/components/SignupPage/EnterUserStepContent.tsx
  src/components/common/Input.tsx
  src/components/common/card/ProfileCard.tsx
  src/pages/OauthRedirectPage.tsx
  src/pages/SigninPage.tsx
  src/routes/PrivateRoutes.tsx
Labels: 💡 Feature

#125 모달 폼 제출 후 닫기, 프롭스 기본값 삭제, 그룹초대장 api수정하였습니다.
  src/components/Modal/AnnouncementEditModal.tsx
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/DetailsScheduleModal.tsx
  src/components/Modal/FreeBoardDetail.tsx
  src/components/Modal/FreeBoardEdit.tsx
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/InvitationGroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/ModalLinkInput.tsx
  src/components/Modal/ModalUrlToggle.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/NotMeIssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/common/modal/AfterApprovalModal.tsx
Labels: :bug: Bug Fix

#126 Refactor: 코드 스플리팅
  src/App.tsx
  src/constants/Page.tsx
Labels: :hammer_and_wrench: Refactor

#129 Feat: 유저 정보 편집 폼 유효성 검증 업데이트
  src/components/Modal/EditProfileModal.tsx
  src/components/SignupPage/EnterUserStepContent.tsx
  src/components/SignupPage/SignupLayout.tsx
  src/hooks/useAxios.ts
Labels: 💡 Feature

#130 Feat: UserPostsPage & UserIssuesPage 그룹필터 추가
  src/components/Post/PostList.tsx
  src/components/common/Filter.tsx
  src/contexts/PageProvider.tsx
  src/hooks/useIssue.ts
  src/pages/UserIssuesPage.tsx
  src/pages/UserPostsPage.tsx
Labels: 💡 Feature

#131 Feat:모달에 달력클릭하면 인풋 값으로 연결
  src/App.tsx
  src/components/Modal/GroupEditModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/Time.tsx
  src/components/common/Nav.tsx
  src/components/common/modal/ModalCalendar.tsx
  src/components/common/modal/ModalCalendarInput.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
Labels: 💡 Feature

#128 그룹모달멤버초대, 쓰레기통삭제버튼, 공지글 스타일변경
  public/assets/Trash.svg
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/DetailsScheduleModal.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/NotMeIssuesModal.tsx
  src/components/Modal/groupMemberInviteModal.tsx
  src/components/common/modal/ModalLayout.tsx
Labels: :bug: Bug Fix, :hammer_and_wrench: Refactor, :art: Style

#132 Fix: 빌드 에러 수정
  src/components/Modal/FreeBoardModal.tsx
  src/components/Post/TeamPostList.tsx
  src/components/Post/UserPostList.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamPostsPage.tsx
Labels: :bug: Bug Fix

#136 Feat: 상세보기 모달 연결
  src/components/Modal/groupMemberInviteModal.tsx
  src/components/Post/PostItem.tsx
  src/components/TeamsPage/TeamBar.tsx
  src/components/kanbanBoard/IssueItem.tsx
  src/components/kanbanBoard/IssueList.tsx
Labels: 💡 Feature

#140 최종모달
  src/components/Modal/AnnouncementEditModal.tsx
  src/components/Modal/DetailsScheduleModal.tsx
  src/components/Modal/FreeBoardDetail.tsx
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/InvitationGroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/NotMeIssuesModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/Modal/groupMemberInviteModal.tsx
  src/components/ModalWrapper.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/common/Button.tsx
  src/components/common/modal/AfterApprovalModal.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalMemberList.tsx
  src/components/landing/LandingNav.tsx
  src/components/landing/Section.tsx
  src/components/landing/SectionItem.tsx
Labels: :bug: Bug Fix, :hammer_and_wrench: Refactor, :art: Style

#141 온보딩 완료git add .
  src/assets/assets/circleDark.svg
  src/assets/assets/circleLight.svg
  src/pages/HomePage.tsx
Labels: 💡 Feature, :art: Style

#144 Soeun
  src/components/MainPage/MainSchedules.tsx
  src/components/MainPage/WeekDisplay.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/pages/HomePage.tsx
Labels: :hammer_and_wrench: Refactor

#146 Fix: UI 수정
  src/components/Post/PostItem.tsx
  src/components/Post/TeamPostList.tsx
  src/components/Post/UserPostList.tsx
  src/components/common/Board.tsx
  src/pages/UserIssuesPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamPostsPage.tsx
Labels: :art: Style

#147 주간달력 안나오는 부분 수정& 온보딩 스타일 수정
  src/components/MainPage/MainSchedules.tsx
  src/components/MainPage/WeekDisplay.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/pages/HomePage.tsx
  src/routes/PrivateRoutes.tsx
Labels: :hammer_and_wrench: Refactor, :art: Style

#148 Fix: 빌드 에러 수정
  src/components/SchedulesPage/GroupFilter.tsx
  src/pages/UserIssuesPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamMainPage.tsx
Labels: :bug: Bug Fix

#153 Fix: 모달 폼 제출 후 새로고침 되지 않던 문제 해결
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/GroupModal.tsx
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/groupMemberInviteModal.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/common/ToolTip.tsx
  src/components/common/sideBar/GroupList.tsx
  src/components/common/sideBar/SideBar.tsx
  src/contexts/PageProvider.tsx
  src/hooks/useMyTeamPage.ts
  src/hooks/useMyTeams.ts
  src/pages/UserIssuesPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamPostsPage.tsx
Labels: :bug: Bug Fix

#155 Fix: 멤버리스트, 회원가입, 마이페이지 기능 문제 전체 수정
  src/App.tsx
  src/components/Modal/EditProfileModal.tsx
  src/components/Modal/ManageTeamHistoryModal.tsx
  src/components/Mypage/MyTeamHistoryTable.tsx
  src/components/SignupPage/EnterUserStepContent.tsx
  src/components/members/MemberRow.tsx
  src/components/members/MemberTable.tsx
Labels: :bug: Bug Fix

#154 Fixed: 일정추가되면 리렌더링 가능, 모달 시간 설정부분 수정
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AddScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/Time.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
Labels: :hammer_and_wrench: Refactor

#157 teamId 문제 해결, 자유게시판 마진값 변경
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/IssuesModal.tsx
Labels: :bug: Bug Fix, :art: Style

#158 홈페이지 케러셀
  src/pages/HomePage.tsx
Labels: 💡 Feature

#159 Fix: 유저 페이지 필터 기능 수정
  src/assets/DarkGroupIcon.tsx
  src/components/common/Filter.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/contexts/PageProvider.tsx
  src/hooks/useIssue.ts
  src/hooks/usePost.ts
  src/pages/UserIssuesPage.tsx
  src/pages/UserMainPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamIssuesPage.tsx
  src/pages/team/TeamMainPage.tsx
Labels: :bug: Bug Fix

#160 코드정리
  src/components/MainPage/MainSchedules.tsx
  src/components/Modal/InvitationGroupModal.tsx
  src/components/SchedulesPage/AddScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/common/Nav.tsx
  src/components/common/NavModal.tsx
  src/components/common/modal/AfterApprovalModal.tsx
Labels: :hammer_and_wrench: Refactor

#166 Feat: 회원탈퇴, 로그아웃 구현
  package-lock.json
  src/components/Modal/ManageTeamHistoryModal.tsx
  src/components/Mypage/DeleteAccountButton.tsx
  src/components/common/ItemDropDown.tsx
  src/components/common/LogoutDropDown.tsx
  src/components/common/Nav.tsx
  src/components/common/SelectBoxDropdown.tsx
  src/components/members/MemberRow.tsx
  src/pages/UserMyPage.tsx
Labels: 💡 Feature

#168 Style: 로그인, 회원가입 페이지 반응형 업데이트
  src/App.tsx
  src/assets/assets/login-banner-icon.png
  src/assets/assets/login-banner-icon.svg
  src/assets/assets/login-banner-logo.svg
  src/components/SignupPage/SignupLayout.tsx
  src/components/common/EntrancePageLayout.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
Labels: :art: Style

#167 댓글 기능 구현 , 대댓글 미구현
  src/components/Modal/FreeBoardDetail.tsx
  src/components/common/modal/Comment.tsx
  src/components/common/modal/CommentItem.tsx
Labels: 💡 Feature

#169 댓글 post요청 후 input창 reset, window.location.reload(); -> useAxios로 수정
  src/components/Modal/IssuesModal.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/common/modal/Comment.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/hooks/useIssue.ts
  src/pages/UserIssuesPage.tsx
  src/pages/team/TeamIssuesPage.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#170 Fix: 마이페이지, 멤버페이지 API 맞춰 수정
  src/components/Modal/ManageTeamHistoryModal.tsx
  src/components/common/Nav.tsx
  src/components/members/MemberTable.tsx
Labels: :bug: Bug Fix

#171 일정 삭제모달 완성, 일정 수정 모달 진행중
  src/assets/EditPenIcon.tsx
  src/assets/Edit_duotone_line@2x.svg
  src/components/Modal/PopupModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ScheduleDeleteModal.tsx
  src/components/SchedulesPage/ScheduleEditModal.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/common/Nav.tsx
  src/components/common/NavModal.tsx
  src/components/common/TextButton.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/contexts/CalenarProvider.tsx
  src/contexts/ModalProvider.tsx
  src/hooks/useAxios.ts
  src/types/iconProps.ts
Labels: 💡 Feature

#172 Fix: window.location.reload() 함수 사용 부분 수정
  src/components/Modal/AnnouncementModal.tsx
  src/components/Modal/FreeBoardModal.tsx
  src/components/Modal/MyIssuesModal.tsx
  src/components/Modal/groupMemberInviteModal.tsx
  src/components/Post/TeamPostList.tsx
  src/components/Post/UserPostList.tsx
  src/components/announcement/AnnouncementItem.tsx
  src/components/announcement/AnnouncementList.tsx
  src/components/announcement/AnnouncementPageList.tsx
  src/components/kanbanBoard/IssueItem.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/pages/UserMainPage.tsx
  src/pages/UserPostsPage.tsx
  src/pages/team/TeamAnnouncementsPage.tsx
  src/pages/team/TeamIssuesPage.tsx
  src/pages/team/TeamMainPage.tsx
  src/pages/team/TeamPostsPage.tsx
  src/types/announcementTypes.ts
Labels: :bug: Bug Fix, :hammer_and_wrench: Refactor

#173 일정수정 모달 기능 완료(랜더링X), 빌드시 오류 수정
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/ScheduleDeleteModal.tsx
  src/components/SchedulesPage/ScheduleEditModal.tsx
  src/components/common/TextButton.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/contexts/CalenarProvider.tsx
Labels: 💡 Feature

#175 Setting: 폰트 셋팅
  src/assets/fonts/Pretendard-Black.woff2
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard-Thin.woff2
  src/assets/fonts/RammettoOne-Regular.ttf
  src/index.css
  src/main.tsx
  src/styles/fonts.css
  src/styles/index.css
Labels: :gear: Setting

#179 Feat: 로딩 페이지 추가
  src/App.tsx
  src/pages/LoadingPage.tsx
Labels: :art: Style

#182 Design: 디자인 수정 및 변경 사항 반영
  src/components/TeamsPage/TeamBar.tsx
  src/components/common/Filter.tsx
  src/components/kanbanBoard/IssueList.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/pages/UserIssuesPage.tsx
Labels: :art: Style

#181 댓글 페이지네이션, 자유게시판 ui 수정
  src/assets/assets/Edit.svg
  src/components/Modal/FreeBoardDetail.tsx
  src/components/Modal/FreeBoardEdit.tsx
  src/components/Modal/InvitationGroupModal.tsx
  src/components/common/modal/AfterApprovalModal.tsx
  src/components/common/modal/Comment.tsx
  src/components/common/modal/CommentItem.tsx
  src/components/common/modal/CommentPageination.tsx
  src/components/common/modal/CommentReply.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ReplyItem.tsx
Labels: 💡 Feature, :hammer_and_wrench: Refactor

#185 초대받은모달 승인하기 클릭시 undefind문제 해결
  src/components/Modal/InvitationGroupModal.tsx
  src/components/common/modal/AfterApprovalModal.tsx
Labels: :bug: Bug Fix

#186 Feat: 채팅 열고 닫기 기능 구현
  .eslintrc.cjs
  index.html
  src/App.tsx
  src/assets/SendIcon.tsx
  src/components/chat/Chat.tsx
  src/components/chat/ChatHeader.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChatListItem.tsx
  src/components/common/Filter.tsx
  src/components/common/PageLayout.tsx
  src/components/kanbanBoard/KanbanBoard.tsx
  src/constants/Page.tsx
  src/contexts/ChatProvider.tsx
  src/contexts/IssueProvider.tsx
  src/contexts/PageProvider.tsx
  src/pages/UserPostsPage.tsx
Labels: 💡 Feature

#187 모달 렌더링
  src/assets/Edit_duotone_line@2x.svg
  src/components/Modal/GroupModal.tsx
  src/components/Modal/PopupModal.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/GroupFilter.tsx
  src/components/SchedulesPage/ScheduleDeleteModal.tsx
  src/components/SchedulesPage/ScheduleEditModal.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/common/TextButton.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/components/common/modal/ProfileModal.tsx
  src/hooks/useScheduleData.ts
Labels: :hammer_and_wrench: Refactor

#192 빌드 오류 수정
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/ScheduleDeleteModal.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/components/common/modal/ModalScheduleCalendarInput.tsx
  src/hooks/useAxios.ts
Labels: :bug: Bug Fix

#196 Update README.md
  README.md
Labels: :gear: Setting

#197 404페이지, 주간 캘린더 오류 해결
  src/App.tsx
  src/components/MainPage/MainSchedules.tsx
  src/components/MainPage/WeekArr.tsx
  src/components/MainPage/WeekDisplay.tsx
  src/components/Modal/ScheduleModal.tsx
  src/components/SchedulesPage/AllDay.tsx
  src/components/SchedulesPage/DateBox.tsx
  src/components/SchedulesPage/ScheduleDeleteModal.tsx
  src/components/SchedulesPage/ScheduleEditModal.tsx
  src/components/SchedulesPage/Schedules.tsx
  src/pages/NotFound.tsx
Labels: :bug: Bug Fix, 💡 Feature
